language: node_js
dist: trusty
node_js:
  - "6"
cache:
  directories:
      - node_modules
before_install:
  - npm install -g ethereumjs-testrpc
  - testrpc &
notifications:
  slack:
      on_change: always
  email: false

